class CONTROLLER:
    """Preferences for the Controller."""
    data_fetched = "DATA FETCHED"
    data_fetched_msg = "Copy Data ready!\n\nCTRL + V in the appropriate network to past your data."
    data_sent = "DATA SENT"
    data_sent_msg = "Copy Data Sent To User(s)!"
    can_not_delete = "ITEM NOT FOUND"
    can_not_delete_msg = "Can not find item to delete:\n{0}"
    delete_item = "DELETE ITEM?"
    delete_item_msg = "ARE YOU SURE YOU WANT TO DELETE:\n{0}"
    error_user_folder = "NOT ABLE TO CREATE SHARE FOLDER"
    error_user_folder_msg = ("Unable to create folder:\n{path}.\n\nIf the path looks correct create this folder "
                             "manually.\n\nIf the path does not look correct fix the SHARED_USERS_FOLDER path in "
                             "config.py\n\nOnce created, restart QuickShare.")
    invalid_entry = "INVALID ENTRY"
    invalid_entry_msg = "USE NAME DOES NOT APPEAR TO BE VALID"
    invalid_name = "INVALID NAME ENTRY"
    invalid_name_msg = "PACKET NAME DOES NOT APPEAR TO BE VALID"
    invalid_note = "INVALID NOTE ENTRY"
    invalid_note_msg = "PACKET NAME APPEARS TO HAVE AN INVALID CHARACTER IN IT'S NAME"
    invalid_pkg_note = "PACKET NOTE DOES NOT APPEAR TO BE VALID"
    missing_users = "MISSING USERS"
    missing_users_msg = "PLEASE ADD A USER BEFORE TRYING TO SEND DATA!"
    notes = "Notes"
    packet_note = "Packet:\n{note}\n\n"
    configured = "Configured"
